### PR TITLE
Fix Billing facade/class conflict in Mmanos\Billing\CustomerBillableTrait\Charges

### LINKED ISSUE #7: Cannot use Mmanos\Billing\Facades\Billing as Billing because the name is already in use
I'm getting this fatal error when trying to charge a customer. Here's the code where it's called:

~~~
$user = Auth::user();

try {
  $user->billing()->withCardToken(Input::get('stripeToken'))->create([
    'email' => $user->email,
  ]);

  $user->charges()->create(19999);
}
catch (Exception $e) {
  return Redirect::back()->withErrors([
    $e->getMessage(),
  ]);
}
~~~

If I made these changes in Charges.php everything works just fine:

~~~
use Mmanos\Billing\Facades\Billing as BillingFacade;
[...]
$gateway_charge = BillingFacade::charge(...
~~~

Do I have something misconfigured, or am I running into a weird edge case?

### PR DESCRIPTION
**Pull request by karlshea**
Updated to use the fully-qualified facade class in the same style as Mmanos\Billing\CustomerBillableTrait\Billing class.

Fixes #7

### CODE REVIEW

**Comment by mmanos** [comment]
Good catch. Thanks for this!

**Comment by dmyers** [comment]
Couldn't it also be aliased, I think most of the time we don't use full paths.

**Comment by karlshea** [comment]
It could be, and that's how I was fixing it in my local copy, but I noticed that you used the full path elsewhere in the namespace so I guessed at the style. I also prefer aliases.

**Comment by dmyers** [comment]
Good point. Works either way so good fix. :+1:

**Comment by karlshea** [comment]
Thanks! Glad I can switch back to the main repo in composer so quickly :-)

**Pull request merged**
